# Generated by Django 3.2.23 on 2024-01-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20240120_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='artists/'),
        ),
    ]
