# Generated by Django 3.2.23 on 2024-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
