# Generated by Django 3.2.23 on 2024-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20240202_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['firstname', 'surname']},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='auctions_turnover_2023_h1_USD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='firstname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'Non-binary')], max_length=1),
        ),
        migrations.AddField(
            model_name='artist',
            name='surname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
