# Generated by Django 3.2.23 on 2024-02-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20240218_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='born',
        ),
    ]
