# Generated by Django 3.2.23 on 2024-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_remove_artist_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='born',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
