# Generated by Django 3.2.23 on 2024-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_artist_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sizeX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sizeY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
