# Generated by Django 3.2.23 on 2024-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_auto_20240309_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='file_field',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, default='without name', max_length=250),
        ),
    ]
