# Generated by Django 3.2.23 on 2024-03-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20240330_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='file_field',
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
