# Generated by Django 3.2.23 on 2024-03-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_auto_20240330_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
