# Generated by Django 3.2.23 on 2024-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_artwork_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
