# Generated by Django 3.2.23 on 2024-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_auto_20240331_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_image_weaviate_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='picture_image_weaviate_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
