# Generated by Django 3.2.23 on 2024-09-08 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_auto_20240414_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='similar_authors_weaviate_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
