# Generated by Django 3.2.23 on 2024-09-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_artist_similar_authors_weaviate_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='similar_authors_weaviate_ids',
            new_name='similar_authors_postgres_ids',
        ),
    ]
