# Generated by Django 3.2.23 on 2024-10-17 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_rename_similar_authors_weaviate_ids_artist_similar_authors_postgres_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='media_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('painting', 'Painting'), ('nft', 'NFT'), ('sculpture', 'Sculpture'), ('digital', 'Digital')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
