# Generated by Django 3.2.23 on 2024-10-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0016_artist_media_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='auctions_turnover_2023_h1_USD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
