# Generated by Django 3.2.23 on 2024-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(null=True, upload_to='artworks/'),
        ),
    ]
